language: node_js
sudo: false

node_js:
  - "0.12"

install:
  - cd eslint-server && npm install && cd ../eslint && npm install && cd ..

script:
  - cd eslint-server && npm run compile && cd ../eslint && npm run compile && cd ..